
/* File generated by gen_cfile.py. Should not be modified. */

#include "ObjDict.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
REAL32 DHT22_Temp[] =		/* Mapped at index 0x2000, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0.0 */
    0x0,	/* 0.0 */
    0x0,	/* 0.0 */
    0x0	/* 0.0 */
  };
REAL32 DHT22_Humi[] =		/* Mapped at index 0x2001, subindex 0x01 - 0x04 */
  {
    0x0,	/* 0.0 */
    0x0,	/* 0.0 */
    0x0,	/* 0.0 */
    0x0	/* 0.0 */
  };
UNS8 Switch[] =		/* Mapped at index 0x2002, subindex 0x01 - 0x02 */
  {
    0x0,	/* 0 */
    0x0	/* 0 */
  };
INTEGER8 Opener[] =		/* Mapped at index 0x2003, subindex 0x01 - 0x03 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS16 Switch_Timeout = 0x2D0;		/* Mapped at index 0x200D, subindex 0x00 */
UNS8 Opener_Timeout = 0xC;		/* Mapped at index 0x200E, subindex 0x00 */
REAL32 Main_Voltage = 0x0;		/* Mapped at index 0x200F, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x24 /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 ObjDict_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 ObjDict_bDeviceNodeId = 0x24;

/**************************************************************************/
/* Array of message processing information */

const UNS8 ObjDict_iam_a_slave = 1;

TIMER_HANDLE ObjDict_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 ObjDict_obj1000 = 0x0;	/* 0 */
                    subindex ObjDict_Index1000[] = 
                     {
                       { RO, CANopen_TYPE_uint32, (void*)&ObjDict_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 ObjDict_obj1001 = 0x0;	/* 0 */
                    subindex ObjDict_Index1001[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&ObjDict_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field. */
                    UNS8 ObjDict_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1003[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    ODCallback_t ObjDict_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex ObjDict_Index1003[] = 
                     {
                       { RW, valueRange_EMC, (void*)&ObjDict_highestSubIndex_obj1003 },
                       { RO, CANopen_TYPE_uint32, (void*)&ObjDict_obj1003[0] },
                       { RO, CANopen_TYPE_uint32, (void*)&ObjDict_obj1003[1] },
                       { RO, CANopen_TYPE_uint32, (void*)&ObjDict_obj1003[2] },
                       { RO, CANopen_TYPE_uint32, (void*)&ObjDict_obj1003[3] }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS16 ObjDict_obj1005 = 0x80;	/* 128 */
                    ODCallback_t ObjDict_Index1005_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex ObjDict_Index1005[] = 
                     {
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1005 }
                     };

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 ObjDict_obj1006 = 0x2710;	/* 10000 */
                    ODCallback_t ObjDict_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex ObjDict_Index1006[] = 
                     {
                       { RW, CANopen_TYPE_uint32, (void*)&ObjDict_obj1006 }
                     };

/* index 0x1008 :   Manufacturer Device Name. */
                    UNS8 ObjDict_obj1008[10] = "AGCON_B1";
                    subindex ObjDict_Index1008[] = 
                     {
                       { RO, CANopen_TYPE_visible_string, (void*)&ObjDict_obj1008 }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 ObjDict_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 ObjDict_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID. */
                    UNS16 ObjDict_obj1014 = 0xA4;	/* 164 */
                    subindex ObjDict_Index1014[] = 
                     {
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1014 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 ObjDict_highestSubIndex_obj1016 = 0;
                    UNS32 ObjDict_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 ObjDict_obj1017 = 0x2710;	/* 10000 */
                    ODCallback_t ObjDict_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex ObjDict_Index1017[] = 
                     {
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 ObjDict_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1018_Vendor_ID = 0x154F12EE;	/* 357503726 */
                    UNS32 ObjDict_obj1018_Product_Code = 0xA6C1;	/* 42689 */
                    UNS32 ObjDict_obj1018_Revision_Number = 0x1;	/* 1 */
                    UNS32 ObjDict_obj1018_Serial_Number = 0x1;	/* 1 */
                    subindex ObjDict_Index1018[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj1018 },
                       { RO, CANopen_TYPE_uint32, (void*)&ObjDict_obj1018_Vendor_ID },
                       { RO, CANopen_TYPE_uint32, (void*)&ObjDict_obj1018_Product_Code },
                       { RO, CANopen_TYPE_uint32, (void*)&ObjDict_obj1018_Revision_Number },
                       { RO, CANopen_TYPE_uint32, (void*)&ObjDict_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 ObjDict_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS16 ObjDict_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x624;	/* 1572 */
                    UNS16 ObjDict_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x5A4;	/* 1444 */
                    subindex ObjDict_Index1200[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj1200 },
                       { RO, CANopen_TYPE_uint16, (void*)&ObjDict_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, CANopen_TYPE_uint16, (void*)&ObjDict_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 ObjDict_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS16 ObjDict_obj1400_COB_ID_used_by_PDO = 0x224;	/* 548 */
                    UNS8 ObjDict_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex ObjDict_Index1400[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj1400 },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1400_COB_ID_used_by_PDO },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1400_Transmission_Type },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1400_Inhibit_Time },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1400_Compatibility_Entry },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1400_Event_Timer },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1400_SYNC_start_value }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 ObjDict_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS16 ObjDict_obj1401_COB_ID_used_by_PDO = 0x324;	/* 804 */
                    UNS8 ObjDict_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex ObjDict_Index1401[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj1401 },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1401_COB_ID_used_by_PDO },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1401_Transmission_Type },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1401_Inhibit_Time },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1401_Compatibility_Entry },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1401_Event_Timer },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1401_SYNC_start_value }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 ObjDict_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS16 ObjDict_obj1402_COB_ID_used_by_PDO = 0x424;	/* 1060 */
                    UNS8 ObjDict_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex ObjDict_Index1402[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj1402 },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1402_COB_ID_used_by_PDO },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1402_Transmission_Type },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1402_Inhibit_Time },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1402_Compatibility_Entry },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1402_Event_Timer },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1402_SYNC_start_value }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 ObjDict_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS16 ObjDict_obj1403_COB_ID_used_by_PDO = 0x524;	/* 1316 */
                    UNS8 ObjDict_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex ObjDict_Index1403[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj1403 },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1403_COB_ID_used_by_PDO },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1403_Transmission_Type },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1403_Inhibit_Time },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1403_Compatibility_Entry },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1403_Event_Timer },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1403_SYNC_start_value }
                     };

/* index 0x1404 :   Receive PDO 5 Parameter. */
                    UNS8 ObjDict_highestSubIndex_obj1404 = 6; /* number of subindex - 1*/
                    UNS16 ObjDict_obj1404_COB_ID_used_by_PDO = 0x225;	/* 549 */
                    UNS8 ObjDict_obj1404_Transmission_Type = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1404_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1404_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1404_Event_Timer = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1404_SYNC_start_value = 0x0;	/* 0 */
                    subindex ObjDict_Index1404[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj1404 },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1404_COB_ID_used_by_PDO },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1404_Transmission_Type },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1404_Inhibit_Time },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1404_Compatibility_Entry },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1404_Event_Timer },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1404_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 ObjDict_highestSubIndex_obj1600 = 1; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1600[] = 
                    {
                      0x20020108	/* 537002248 */
                    };
                    subindex ObjDict_Index1600[] = 
                     {
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj1600 },
                       { RW, CANopen_TYPE_uint32, (void*)&ObjDict_obj1600[0] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 ObjDict_highestSubIndex_obj1601 = 1; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1601[] = 
                    {
                      0x20020208	/* 537002504 */
                    };
                    subindex ObjDict_Index1601[] = 
                     {
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj1601 },
                       { RW, CANopen_TYPE_uint32, (void*)&ObjDict_obj1601[0] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 ObjDict_highestSubIndex_obj1602 = 1; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1602[] = 
                    {
                      0x20030108	/* 537067784 */
                    };
                    subindex ObjDict_Index1602[] = 
                     {
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj1602 },
                       { RW, CANopen_TYPE_uint32, (void*)&ObjDict_obj1602[0] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 ObjDict_highestSubIndex_obj1603 = 1; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1603[] = 
                    {
                      0x20030208	/* 537068040 */
                    };
                    subindex ObjDict_Index1603[] = 
                     {
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj1603 },
                       { RW, CANopen_TYPE_uint32, (void*)&ObjDict_obj1603[0] }
                     };

/* index 0x1604 :   Receive PDO 5 Mapping. */
                    UNS8 ObjDict_highestSubIndex_obj1604 = 1; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1604[] = 
                    {
                      0x20030308	/* 537068296 */
                    };
                    subindex ObjDict_Index1604[] = 
                     {
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj1604 },
                       { RW, CANopen_TYPE_uint32, (void*)&ObjDict_obj1604[0] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 ObjDict_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS16 ObjDict_obj1800_COB_ID_used_by_PDO = 0x1A4;	/* 420 */
                    UNS8 ObjDict_obj1800_Transmission_Type = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t ObjDict_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex ObjDict_Index1800[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj1800 },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1800_COB_ID_used_by_PDO },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1800_Transmission_Type },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1800_Inhibit_Time },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1800_Compatibility_Entry },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1800_Event_Timer },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1800_SYNC_start_value }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 ObjDict_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS16 ObjDict_obj1801_COB_ID_used_by_PDO = 0x2A4;	/* 676 */
                    UNS8 ObjDict_obj1801_Transmission_Type = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t ObjDict_Index1801_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex ObjDict_Index1801[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj1801 },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1801_COB_ID_used_by_PDO },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1801_Transmission_Type },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1801_Inhibit_Time },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1801_Compatibility_Entry },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1801_Event_Timer },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1801_SYNC_start_value }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 ObjDict_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS16 ObjDict_obj1802_COB_ID_used_by_PDO = 0x3A4;	/* 932 */
                    UNS8 ObjDict_obj1802_Transmission_Type = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t ObjDict_Index1802_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex ObjDict_Index1802[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj1802 },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1802_COB_ID_used_by_PDO },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1802_Transmission_Type },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1802_Inhibit_Time },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1802_Compatibility_Entry },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1802_Event_Timer },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1802_SYNC_start_value }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 ObjDict_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS16 ObjDict_obj1803_COB_ID_used_by_PDO = 0x4A4;	/* 1188 */
                    UNS8 ObjDict_obj1803_Transmission_Type = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t ObjDict_Index1803_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex ObjDict_Index1803[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj1803 },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1803_COB_ID_used_by_PDO },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1803_Transmission_Type },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1803_Inhibit_Time },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1803_Compatibility_Entry },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1803_Event_Timer },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1803_SYNC_start_value }
                     };

/* index 0x1804 :   Transmit PDO 5 Parameter. */
                    UNS8 ObjDict_highestSubIndex_obj1804 = 6; /* number of subindex - 1*/
                    UNS16 ObjDict_obj1804_COB_ID_used_by_PDO = 0x1A5;	/* 421 */
                    UNS8 ObjDict_obj1804_Transmission_Type = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1804_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1804_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1804_Event_Timer = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1804_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t ObjDict_Index1804_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex ObjDict_Index1804[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj1804 },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1804_COB_ID_used_by_PDO },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1804_Transmission_Type },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1804_Inhibit_Time },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1804_Compatibility_Entry },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1804_Event_Timer },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1804_SYNC_start_value }
                     };

/* index 0x1805 :   Transmit PDO 6 Parameter. */
                    UNS8 ObjDict_highestSubIndex_obj1805 = 6; /* number of subindex - 1*/
                    UNS16 ObjDict_obj1805_COB_ID_used_by_PDO = 0x2A5;	/* 677 */
                    UNS8 ObjDict_obj1805_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 ObjDict_obj1805_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1805_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1805_Event_Timer = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1805_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t ObjDict_Index1805_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex ObjDict_Index1805[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj1805 },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1805_COB_ID_used_by_PDO },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1805_Transmission_Type },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1805_Inhibit_Time },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1805_Compatibility_Entry },
                       { RW, CANopen_TYPE_uint16, (void*)&ObjDict_obj1805_Event_Timer },
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_obj1805_SYNC_start_value }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 ObjDict_highestSubIndex_obj1A00 = 2; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1A00[] = 
                    {
                      0x20000120,	/* 536871200 */
                      0x20010120	/* 536936736 */
                    };
                    subindex ObjDict_Index1A00[] = 
                     {
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj1A00 },
                       { RW, CANopen_TYPE_uint32, (void*)&ObjDict_obj1A00[0] },
                       { RW, CANopen_TYPE_uint32, (void*)&ObjDict_obj1A00[1] }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 ObjDict_highestSubIndex_obj1A01 = 2; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1A01[] = 
                    {
                      0x20000220,	/* 536871456 */
                      0x20010220	/* 536936992 */
                    };
                    subindex ObjDict_Index1A01[] = 
                     {
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj1A01 },
                       { RW, CANopen_TYPE_uint32, (void*)&ObjDict_obj1A01[0] },
                       { RW, CANopen_TYPE_uint32, (void*)&ObjDict_obj1A01[1] }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 ObjDict_highestSubIndex_obj1A02 = 2; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1A02[] = 
                    {
                      0x20000320,	/* 536871712 */
                      0x20010320	/* 536937248 */
                    };
                    subindex ObjDict_Index1A02[] = 
                     {
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj1A02 },
                       { RW, CANopen_TYPE_uint32, (void*)&ObjDict_obj1A02[0] },
                       { RW, CANopen_TYPE_uint32, (void*)&ObjDict_obj1A02[1] }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 ObjDict_highestSubIndex_obj1A03 = 2; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1A03[] = 
                    {
                      0x20000420,	/* 536871968 */
                      0x20010420	/* 536937504 */
                    };
                    subindex ObjDict_Index1A03[] = 
                     {
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj1A03 },
                       { RW, CANopen_TYPE_uint32, (void*)&ObjDict_obj1A03[0] },
                       { RW, CANopen_TYPE_uint32, (void*)&ObjDict_obj1A03[1] }
                     };

/* index 0x1A04 :   Transmit PDO 5 Mapping. */
                    UNS8 ObjDict_highestSubIndex_obj1A04 = 1; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1A04[] = 
                    {
                      0x200F0020	/* 537853984 */
                    };
                    subindex ObjDict_Index1A04[] = 
                     {
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj1A04 },
                       { RW, CANopen_TYPE_uint32, (void*)&ObjDict_obj1A04[0] }
                     };

/* index 0x1A05 :   Transmit PDO 6 Mapping. */
                    UNS8 ObjDict_highestSubIndex_obj1A05 = 5; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1A05[] = 
                    {
                      0x20020108,	/* 537002248 */
                      0x20020208,	/* 537002504 */
                      0x20030108,	/* 537067784 */
                      0x20030208,	/* 537068040 */
                      0x20030308	/* 537068296 */
                    };
                    subindex ObjDict_Index1A05[] = 
                     {
                       { RW, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj1A05 },
                       { RW, CANopen_TYPE_uint32, (void*)&ObjDict_obj1A05[0] },
                       { RW, CANopen_TYPE_uint32, (void*)&ObjDict_obj1A05[1] },
                       { RW, CANopen_TYPE_uint32, (void*)&ObjDict_obj1A05[2] },
                       { RW, CANopen_TYPE_uint32, (void*)&ObjDict_obj1A05[3] },
                       { RW, CANopen_TYPE_uint32, (void*)&ObjDict_obj1A05[4] }
                     };

/* index 0x2000 :   Mapped variable DHT22 Temp */
                    UNS8 ObjDict_highestSubIndex_obj2000 = 4; /* number of subindex - 1*/
                    ODCallback_t DHT22_Temp_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex ObjDict_Index2000[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj2000 },
                       { RO, CANopen_TYPE_real32, (void*)&DHT22_Temp[0] },
                       { RO, CANopen_TYPE_real32, (void*)&DHT22_Temp[1] },
                       { RO, CANopen_TYPE_real32, (void*)&DHT22_Temp[2] },
                       { RO, CANopen_TYPE_real32, (void*)&DHT22_Temp[3] }
                     };

/* index 0x2001 :   Mapped variable DHT22 Humi */
                    UNS8 ObjDict_highestSubIndex_obj2001 = 4; /* number of subindex - 1*/
                    subindex ObjDict_Index2001[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj2001 },
                       { RO, CANopen_TYPE_real32, (void*)&DHT22_Humi[0] },
                       { RO, CANopen_TYPE_real32, (void*)&DHT22_Humi[1] },
                       { RO, CANopen_TYPE_real32, (void*)&DHT22_Humi[2] },
                       { RO, CANopen_TYPE_real32, (void*)&DHT22_Humi[3] }
                     };

/* index 0x2002 :   Mapped variable Switch */
                    UNS8 ObjDict_highestSubIndex_obj2002 = 2; /* number of subindex - 1*/
                    ODCallback_t Switch_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex ObjDict_Index2002[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj2002 },
                       { RW, CANopen_TYPE_uint8, (void*)&Switch[0] },
                       { RW, CANopen_TYPE_uint8, (void*)&Switch[1] }
                     };

/* index 0x2003 :   Mapped variable Opener */
                    UNS8 ObjDict_highestSubIndex_obj2003 = 3; /* number of subindex - 1*/
                    ODCallback_t Opener_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex ObjDict_Index2003[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&ObjDict_highestSubIndex_obj2003 },
                       { RW, CANopen_TYPE_int8, (void*)&Opener[0] },
                       { RW, CANopen_TYPE_int8, (void*)&Opener[1] },
                       { RW, CANopen_TYPE_int8, (void*)&Opener[2] }
                     };

/* index 0x200D :   Mapped variable Switch Timeout */
                    subindex ObjDict_Index200D[] = 
                     {
                       { RW, CANopen_TYPE_uint16, (void*)&Switch_Timeout }
                     };

/* index 0x200E :   Mapped variable Opener Timeout */
                    subindex ObjDict_Index200E[] = 
                     {
                       { RW, CANopen_TYPE_uint8, (void*)&Opener_Timeout }
                     };

/* index 0x200F :   Mapped variable Main Voltage */
                    ODCallback_t Main_Voltage_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex ObjDict_Index200F[] = 
                     {
                       { RO, CANopen_TYPE_real32, (void*)&Main_Voltage }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const subindex * ObjDict_scanIndexOD (UNS16 wIndex, UNS8 *size, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	subindex *si= NULL;
	switch(wIndex){
		case 0x1000: si = ObjDict_Index1000; *size= sizeof(ObjDict_Index1000)/sizeof(ObjDict_Index1000[0]); break;
		case 0x1001: si = ObjDict_Index1001; *size= sizeof(ObjDict_Index1001)/sizeof(ObjDict_Index1001[0]); break;
		case 0x1003: si = ObjDict_Index1003; *size= sizeof(ObjDict_Index1003)/sizeof(ObjDict_Index1003[0]); *callbacks = ObjDict_Index1003_callbacks; break;
		case 0x1005: si = ObjDict_Index1005; *size= sizeof(ObjDict_Index1005)/sizeof(ObjDict_Index1005[0]); *callbacks = ObjDict_Index1005_callbacks; break;
		case 0x1006: si = ObjDict_Index1006; *size= sizeof(ObjDict_Index1006)/sizeof(ObjDict_Index1006[0]); *callbacks = ObjDict_Index1006_callbacks; break;
		case 0x1008: si = ObjDict_Index1008; *size= sizeof(ObjDict_Index1008)/sizeof(ObjDict_Index1008[0]); break;
		case 0x1014: si = ObjDict_Index1014; *size= sizeof(ObjDict_Index1014)/sizeof(ObjDict_Index1014[0]); break;
		case 0x1017: si = ObjDict_Index1017; *size= sizeof(ObjDict_Index1017)/sizeof(ObjDict_Index1017[0]); *callbacks = ObjDict_Index1017_callbacks; break;
		case 0x1018: si = ObjDict_Index1018; *size= sizeof(ObjDict_Index1018)/sizeof(ObjDict_Index1018[0]); break;
		case 0x1200: si = ObjDict_Index1200; *size= sizeof(ObjDict_Index1200)/sizeof(ObjDict_Index1200[0]); break;
		case 0x1400: si = ObjDict_Index1400; *size= sizeof(ObjDict_Index1400)/sizeof(ObjDict_Index1400[0]); break;
		case 0x1401: si = ObjDict_Index1401; *size= sizeof(ObjDict_Index1401)/sizeof(ObjDict_Index1401[0]); break;
		case 0x1402: si = ObjDict_Index1402; *size= sizeof(ObjDict_Index1402)/sizeof(ObjDict_Index1402[0]); break;
		case 0x1403: si = ObjDict_Index1403; *size= sizeof(ObjDict_Index1403)/sizeof(ObjDict_Index1403[0]); break;
		case 0x1404: si = ObjDict_Index1404; *size= sizeof(ObjDict_Index1404)/sizeof(ObjDict_Index1404[0]); break;
		case 0x1600: si = ObjDict_Index1600; *size= sizeof(ObjDict_Index1600)/sizeof(ObjDict_Index1600[0]); break;
		case 0x1601: si = ObjDict_Index1601; *size= sizeof(ObjDict_Index1601)/sizeof(ObjDict_Index1601[0]); break;
		case 0x1602: si = ObjDict_Index1602; *size= sizeof(ObjDict_Index1602)/sizeof(ObjDict_Index1602[0]); break;
		case 0x1603: si = ObjDict_Index1603; *size= sizeof(ObjDict_Index1603)/sizeof(ObjDict_Index1603[0]); break;
		case 0x1604: si = ObjDict_Index1604; *size= sizeof(ObjDict_Index1604)/sizeof(ObjDict_Index1604[0]); break;
		case 0x1800: si = ObjDict_Index1800; *size= sizeof(ObjDict_Index1800)/sizeof(ObjDict_Index1800[0]); *callbacks = ObjDict_Index1800_callbacks; break;
		case 0x1801: si = ObjDict_Index1801; *size= sizeof(ObjDict_Index1801)/sizeof(ObjDict_Index1801[0]); *callbacks = ObjDict_Index1801_callbacks; break;
		case 0x1802: si = ObjDict_Index1802; *size= sizeof(ObjDict_Index1802)/sizeof(ObjDict_Index1802[0]); *callbacks = ObjDict_Index1802_callbacks; break;
		case 0x1803: si = ObjDict_Index1803; *size= sizeof(ObjDict_Index1803)/sizeof(ObjDict_Index1803[0]); *callbacks = ObjDict_Index1803_callbacks; break;
		case 0x1804: si = ObjDict_Index1804; *size= sizeof(ObjDict_Index1804)/sizeof(ObjDict_Index1804[0]); *callbacks = ObjDict_Index1804_callbacks; break;
		case 0x1805: si = ObjDict_Index1805; *size= sizeof(ObjDict_Index1805)/sizeof(ObjDict_Index1805[0]); *callbacks = ObjDict_Index1805_callbacks; break;
		case 0x1A00: si = ObjDict_Index1A00; *size= sizeof(ObjDict_Index1A00)/sizeof(ObjDict_Index1A00[0]); break;
		case 0x1A01: si = ObjDict_Index1A01; *size= sizeof(ObjDict_Index1A01)/sizeof(ObjDict_Index1A01[0]); break;
		case 0x1A02: si = ObjDict_Index1A02; *size= sizeof(ObjDict_Index1A02)/sizeof(ObjDict_Index1A02[0]); break;
		case 0x1A03: si = ObjDict_Index1A03; *size= sizeof(ObjDict_Index1A03)/sizeof(ObjDict_Index1A03[0]); break;
		case 0x1A04: si = ObjDict_Index1A04; *size= sizeof(ObjDict_Index1A04)/sizeof(ObjDict_Index1A04[0]); break;
		case 0x1A05: si = ObjDict_Index1A05; *size= sizeof(ObjDict_Index1A05)/sizeof(ObjDict_Index1A05[0]); break;
		case 0x2000: si = ObjDict_Index2000; *size= sizeof(ObjDict_Index2000)/sizeof(ObjDict_Index2000[0]); *callbacks = DHT22_Temp_callbacks; break;
		case 0x2001: si = ObjDict_Index2001; *size= sizeof(ObjDict_Index2001)/sizeof(ObjDict_Index2001[0]); break;
		case 0x2002: si = ObjDict_Index2002; *size= sizeof(ObjDict_Index2002)/sizeof(ObjDict_Index2002[0]); *callbacks = Switch_callbacks; break;
		case 0x2003: si = ObjDict_Index2003; *size= sizeof(ObjDict_Index2003)/sizeof(ObjDict_Index2003[0]); *callbacks = Opener_callbacks; break;
		case 0x200D: si = ObjDict_Index200D; *size= sizeof(ObjDict_Index200D)/sizeof(ObjDict_Index200D[0]); break;
		case 0x200E: si = ObjDict_Index200E; *size= sizeof(ObjDict_Index200E)/sizeof(ObjDict_Index200E[0]); break;
		case 0x200F: si = ObjDict_Index200F; *size= sizeof(ObjDict_Index200F)/sizeof(ObjDict_Index200F[0]); *callbacks = Main_Voltage_callbacks; break;
		default:
			return NULL;
	}
	return si;
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status ObjDict_PDO_status[6] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

CO_Data ObjDict_Data = CANOPEN_NODE_DATA_INITIALIZER(ObjDict);

UNS8 ObjDict_DataSize(const subindex *s) {
  if(s->bDataType==valueRange_EMC) return 1;
  else return 0;
}

