
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef OBJDICT_H
#define OBJDICT_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 ObjDict_valueRangeTest (UNS8 typeValue, void * value);
const subindex * ObjDict_scanIndexOD (UNS16 wIndex, UNS8 *size, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data ObjDict_Data;
extern REAL32 DHT22_Temp[4];		/* Mapped at index 0x2000, subindex 0x01 - 0x04 */
extern REAL32 DHT22_Humi[4];		/* Mapped at index 0x2001, subindex 0x01 - 0x04 */
extern UNS8 Switch[2];		/* Mapped at index 0x2002, subindex 0x01 - 0x02 */
extern INTEGER8 Opener[3];		/* Mapped at index 0x2003, subindex 0x01 - 0x03 */
extern UNS16 Switch_Timeout;		/* Mapped at index 0x200D, subindex 0x00*/
extern UNS8 Opener_Timeout;		/* Mapped at index 0x200E, subindex 0x00*/
extern REAL32 Main_Voltage;		/* Mapped at index 0x200F, subindex 0x00*/

#endif // OBJDICT_H
